test_id: port_security
test_name: 802.1x auth check
device: switch1
checks:
  - name: 802.1x is enabled
    data_source: port_security
    path: ["Ethernet1", "dot1x_enabled"]
    expected: "True"
  - name: Auth VLAN is correct
    data_source: port_security
    path: ["Ethernet1", "auth_vlan"]
    expected: "100"